### 조회
GET http://localhost:8081/api/projects

### 테스트
GET http://localhost:8081/test

### 인증 테스트
GET http://localhost:8081/api/test
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc4MDMwMjg0MiwiZXhwIjoxNzgwMzA2NDQyfQ.BIuWXqoePhtN4pobxjmcYMeYAWY90xtgc-kMjhMldV0

### 생성
POST http://localhost:8081/api/projects
Content-Type: application/json

{
  "title":"Colossam",
  "techStack":"Unity, C#",
  "description":"콜로세움 컨셉 배틀 게임"
}

### 생성
POST http://localhost:8081/api/projects
Content-Type: application/json

{
  "title":"Scrap-pear",
  "techStack":"Unity, C#",
  "description":"조선시대 리썰류 게임"
}


### 수정
PUT http://localhost:8081/api/projects/1
Content-Type: application/json

{
  "title":"Colossam Remaster",
  "techStack":"Unity, C#",
  "description":"업데이트 테스트"
}

### 삭제
DELETE http://localhost:8081/api/projects/1

### 회원가입
POST http://localhost:8081/api/auth/signup
Content-Type: application/json

{
  "username": "admin",
  "password": "ss6852"
}

### 로그인
POST http://localhost:8081/api/auth/login
Content-Type: application/json

{
"username":"admin",
"password":"1234"
}

### 포스트
GET http://localhost:8081/api/posts