spring:
  application:
    name: backend

  config:
    import: optional:application-secret.yaml

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

server:
  port: 8081

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true